# Generated by Django 2.1.7 on 2019-03-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govContract', models.CharField(max_length=255, verbose_name='Гос. контракт')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('startContract', models.DateField(verbose_name='Действие контракта с')),
                ('stopContract', models.DateField(verbose_name='Дата окончания контракта')),
                ('openContract', models.BooleanField(verbose_name='Закрыть контракт')),
                ('residue', models.FloatField(verbose_name='Остаток')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.BigIntegerField(verbose_name='ИНН')),
                ('ogrn', models.BigIntegerField(verbose_name='ОГРН')),
                ('kpp', models.BigIntegerField(verbose_name='КПП')),
                ('oktmo', models.BigIntegerField(verbose_name='ОКТМО')),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='ogrn',
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование контрагента'),
        ),
    ]
